### ISSUE TITLE
CORS header for https://ethgasstation.info/json/ethgasAPI.json

### ISSUE THREAD

**Issue by eepstein** [ethgasstation/ethgasstation-adaptive-oracle#12]
Adding a CORS header that allows calls from other domains would make 
   https://ethgasstation.info/json/ethgasAPI.json
more useful.
Was there are reason it wasn't added, or was that just an oversight ?

Thanks!

**Comment by bamos01** [comment]
Just an oversite

**Comment by eepstein** [comment]
Ah.  May I submit a patch for the httpd.conf (or similar) ?

**Comment by ethgasstation** [comment]
yes - of course- but I think i fixed it on my .conf file - which isnt part of the repo

**Comment by eepstein** [comment]
ah, right.  

looking forward to the update.  

thanks!
