### ISSUE TITLE
Add script to create database

### ISSUE THREAD

**Issue by fvictorio** [ethgasstation/ethgasstation-adaptive-oracle#4]
It seems like this supposes that mysql has a database (`tx`) and some tables. Unless I missed something, there seems to be no way to create those automatically, or is there?

In case there's not, I'd suggest adding a script (or some migrations directory that can be used with some tool) that creates the database and the proper tables.

**Comment by ethgasstation** [comment]
In the file egs_ref.py  - there is code that will create the mysql tables that you need if they don't exist.  But you do need to manually create a user named 'ethgas' with password 'station' and create a database called 'tx' - try adding the database 'tx' and let me know if it works.

**Comment by fvictorio** [comment]
I had created the `tx` database but it was complaining about the table. But it seems like the problem was on my side, I _think_ it was because I was using virtualenv. I just installed the requirements using `pip3 --user -r requirements.txt` and it worked. Thanks!
